export enum MutationTypes {
  SET_BALANCES_FIRST_LOAD = 'SET_BALANCES_FIRST_LOAD',
  SET_STAKING_BALANCES_FIRST_LOAD = 'SET_STAKING_BALANCES_FIRST_LOAD',
  SET_PRICES_FIRST_LOAD = 'SET_PRICES_FIRST_LOAD',
  RESET_STATE = 'RESET_STATE',
}
