name: Deploy to Preview Channel

on: pull_request

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}
      - run: git submodule init && git submodule update

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build:web

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERIS_HQ }}"
          target: prod
          expires: 7d
          projectId: emeris-hq
