name: Deploy to Preview Channel

on: pull_request

jobs:
  build_and_deploy:
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}
      - run: git submodule init && git submodule update

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: |
            ./yarn.lock
      - run: yarn --frozen-lockfile

      - name: build artifacts
        continue-on-error: true
        run: NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" yarn build:web
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity

      - name: Deploy
        continue-on-error: true
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERIS_HQ }}'
          target: extension
          expires: 7d
          projectId: emeris-hq
