name: Extension Build Dev
on:
  push:
    branches:
      - develop
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  Extension-Build:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}
      - run: git submodule init && git submodule update

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --frozen-lockfile

      - name: build artifacts
        run: NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" npm run build
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity

      - uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: ./dist
          filename: release.zip

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: 'latest'
          prerelease: true
          title: 'Development Build'
          files: |
            ./dist/release.zip
