name: Extension Test
on:
  pull_request:
  workflow_dispatch:
jobs:
  Extension-Test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}

      - run: git submodule init && git submodule update

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: build artifacts
        run: |
          yarn install
          NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" EXTENSION_ID="cklkpejioojjeiigffappdlcmnonmjek" yarn build
        env:
          # Put in secrets
          VITE_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VITE_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity
          VITE_ENCRYPTION_SALT: 8mbL9mEnOTXdiwvgXvgv

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:e2e -- --workers=2
        env:
          EXTENSION_ID: 'cklkpejioojjeiigffappdlcmnonmjek'
          VITE_UNSECURE_KEYS: true # key encryption is built to avoid brute force. but e2e is relying on parallelizm

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
