name: Extension Test
on: pull_request
jobs:
  Extension-Test:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}

      - run: git submodule init && git submodule update

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: |
            ./yarn.lock
      - run: yarn --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: build artifacts
        run: |
          NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" yarn build
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity
          VITE_UNSECURE_KEYS: true # key encryption is built to avoid brute force. but e2e is relying on parallelizm

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:e2e
        env: 
          EXTENSION_ID: 'cklkpejioojjeiigffappdlcmnonmjek'

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
