name: Extension Test
on: 
  pull_request
jobs:
  Extension-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Add checkout key for demeris repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEMERIS_SSH_PRIVATE_KEY }}

      - run: git submodule init && git submodule update

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          # cache: 'yarn'
      - run: yarn --frozen-lockfile
      
      - name: Install Playwright
        run: npx playwright install chromium --with-deps
        
      - name: build artifacts
        run: |
          NODE_OPTIONS="--max_old_space_size=8192" NODE_ENV="production" npm run build
        env:
          # Put in secrets
          VUE_APP_EMERIS_PROD_ENDPOINT: https://api.emeris.com/v1
          VUE_APP_EMERIS_PROD_LIQUIDITY_ENDPOINT: https://api.emeris.com/v1/liquidity

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:e2e
        env: 
          EXTENSION_ID: 'majdpimiaehlcejkaoeedbhdiklflkng'

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30